### ISSUE TITLE
problems compiling the mooncl

### ISSUE THREAD

**Issue by tuxd3v** [stetre/mooncl#1]
I was trying to experiment opencl on ARM device.

My lua5.3-dev package with lua headers are in /usr/include/lua5.3

I don't know, why but it enters in a recursive make until exaust the ram memory..
"
make[38]: Entering directory '/home/rock64/Desktop/mooncl'
make build
make[39]: Entering directory '/home/rock64/Desktop/mooncl'
make build
make[40]: Entering directory '/home/rock64/Desktop/mooncl'
make build
make[41]: Entering directory '/home/rock64/Desktop/mooncl'
make build
make[42]: Entering directory '/home/rock64/Desktop/mooncl'
make build
make[43]: Entering directory '/home/rock64/Desktop/mooncl'
make build
"
I need to kill him.
"
(...)
Makefile:5: recipe for target 'build' failed
make[495]: *** [build] Interrupt
Makefile:5: recipe for target 'build' failed
make[494]: *** [build] Interrupt
Makefile:5: recipe for target 'build' failed
make[493]: *** [build] Interrupt
Makefile:5: recipe for target 'build' failed
make[492]: *** [build] Interrupt
Makefile:5: recipe for target 'build' failed
make[491]: *** [build] Interrupt
Makefile:5: recipe for target 'build' failed
make[490]: *** [build] Interrupt
Makefile:5: recipe for target 'build' failed
(...)
"

How could I compile this project.
I am trying, no root Makefile.

make
also 
make build

It doesn't compile.

Any help?
Thanks in Advance
Regards

**Comment by stetre** [comment]
duplicate (see issue #2)
