### ISSUE TITLE
Problems trying to Compile project

### ISSUE THREAD

**Issue by tuxd3v** [stetre/mooncl#2]
I was trying to experiment opencl on ARM device.

My lua5.3-dev package with lua headers are in /usr/include/lua5.3

I don't know, why but it enters in a recursive make until exaust the ram memory..
"
make[38]: Entering directory '/home/rock64/Desktop/mooncl'
make build
make[39]: Entering directory '/home/rock64/Desktop/mooncl'
make build
make[40]: Entering directory '/home/rock64/Desktop/mooncl'
make build
make[41]: Entering directory '/home/rock64/Desktop/mooncl'
make build
make[42]: Entering directory '/home/rock64/Desktop/mooncl'
make build
make[43]: Entering directory '/home/rock64/Desktop/mooncl'
make build
"
I need to kill him.
"
(...)
Makefile:5: recipe for target 'build' failed
make[495]: *** [build] Interrupt
Makefile:5: recipe for target 'build' failed
make[494]: *** [build] Interrupt
Makefile:5: recipe for target 'build' failed
make[493]: *** [build] Interrupt
Makefile:5: recipe for target 'build' failed
make[492]: *** [build] Interrupt
Makefile:5: recipe for target 'build' failed
make[491]: *** [build] Interrupt
Makefile:5: recipe for target 'build' failed
make[490]: *** [build] Interrupt
Makefile:5: recipe for target 'build' failed
(...)
"

How could I compile this project.
I am trying, no root Makefile.

make
also 
make build

It doesn't compile.

Any help?
Thanks in Advance
Regards

**Comment by stetre** [comment]
That's strange. Did you execute make from the mooncl base directory?

**Comment by tuxd3v** [comment]
After cloning,
Without any modification,
it doesn't find some headers:
$ make

make[1]: Entering directory '/home/rock64/Desktop/mooncl/src'
cc -O2 -Wall -Wextra -Wpedantic -std=gnu99 -DLUAVER=5.3 -fpic -DLINUX -I./include   -c -o enums.o enums.c
In file included from internal.h:39:0,
                 from enums.c:26:
mooncl.h:33:10: fatal error: lua.h: No such file or directory
 #include <lua.h>
          ^~~~~~~

If I go in src/Makefile and add -I/usr/include/

it start to looping recursively.

It theare a way to tell root Makefile were are the headerfiles?

**Comment by stetre** [comment]
If your Lua headers are in /usr/include/lua5.3 you should add -I/usr/include/lua53 to the INCDIR variable in src/Makefile (line 44), ie:

    INCDIR = -I./include -I/usr/include/lua5.3

Alternatively, if you are not using multiple Lua versions, you could just install the Lua headers in a standard location such as /usr/include or /usr/local/include.

**Comment by tuxd3v** [comment]
Hello,
In first place, thanks for your reply.

I have included that in src/Makefile, but some how it won't work...
Later, I deleted the old clone of mooncl, I git cloned it again, and added the needed in src/Makefile, suddenly, it worked OK, I think..

Them sudo make install
it installed on /usr/local, as expected.

I checked your test script on page project:
$ lua ./hello.lua
20 + 30 = 50

other example:
$ lua examples/platforminfo.lua

Found 1 platform.

platform no. 1:
- name: ARM Platform
- vendor: ARM
- version: OpenCL 1.2 v1.r14p0-01rel0-git(966ed26).f44c85cb3d2ceb87e8be88e7592755c3
- profile: FULL_PROFILE
- extensions: 
   cl_khr_global_int32_base_atomics
   cl_khr_global_int32_extended_atomics
   cl_khr_local_int32_base_atomics
   cl_khr_local_int32_extended_atomics
   cl_khr_byte_addressable_store
   cl_khr_3d_image_writes
   cl_khr_fp64
   cl_khr_int64_base_atomics
   cl_khr_int64_extended_atomics
   cl_khr_fp16
   cl_khr_gl_sharing
   cl_khr_icd
   cl_khr_egl_event
   cl_khr_egl_image
   cl_khr_image2d_from_buffer
   cl_arm_core_id
   cl_arm_printf
   cl_arm_thread_limit_hint
   cl_arm_non_uniform_work_group_size
   cl_arm_import_memory
- devices: 
   1: Mali-T860 (OpenCL 1.2 v1.r14p0-01rel0-git(966ed26).f44c85cb3d2ceb87e8be88e7592755c3 - FULL_PROFILE)


I think this was the expected?
Many Many thanks :)

**Comment by stetre** [comment]
Yes, it looks good :)
I'll add the alternative include path to the Makefile in the master branch, so the next time you clone it it should work out of the box.

**Comment by tuxd3v** [comment]
Thankyou very much for that!
I confirm its now, ok , smooth :)

Also I made a Tutorial, about mooncl, its a short post, on Pine Forum:
https://forum.pine64.org/showthread.php?tid=6749

Best Regards,

**Comment by stetre** [comment]
Thank you!
